// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.2
// source: internal/proto/ensync.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EnSyncService_Connect_FullMethodName            = "/ensync.EnSyncService/Connect"
	EnSyncService_Heartbeat_FullMethodName          = "/ensync.EnSyncService/Heartbeat"
	EnSyncService_PublishMessage_FullMethodName     = "/ensync.EnSyncService/PublishMessage"
	EnSyncService_Subscribe_FullMethodName          = "/ensync.EnSyncService/Subscribe"
	EnSyncService_Unsubscribe_FullMethodName        = "/ensync.EnSyncService/Unsubscribe"
	EnSyncService_AcknowledgeMessage_FullMethodName = "/ensync.EnSyncService/AcknowledgeMessage"
	EnSyncService_DeferMessage_FullMethodName       = "/ensync.EnSyncService/DeferMessage"
	EnSyncService_DiscardMessage_FullMethodName     = "/ensync.EnSyncService/DiscardMessage"
	EnSyncService_ReplayMessage_FullMethodName      = "/ensync.EnSyncService/ReplayMessage"
	EnSyncService_PauseMessages_FullMethodName      = "/ensync.EnSyncService/PauseMessages"
	EnSyncService_ContinueMessages_FullMethodName   = "/ensync.EnSyncService/ContinueMessages"
)

// EnSyncServiceClient is the client API for EnSyncService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Main EnSync service for client communication
type EnSyncServiceClient interface {
	// Connection & Authentication
	Connect(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (*ConnectResponse, error)
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	// Message Publishing
	PublishMessage(ctx context.Context, in *PublishMessageRequest, opts ...grpc.CallOption) (*PublishMessageResponse, error)
	// Message Subscription - Returns a stream of messages
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MessageStreamResponse], error)
	Unsubscribe(ctx context.Context, in *UnsubscribeRequest, opts ...grpc.CallOption) (*UnsubscribeResponse, error)
	// Message Management
	AcknowledgeMessage(ctx context.Context, in *AcknowledgeRequest, opts ...grpc.CallOption) (*AcknowledgeResponse, error)
	DeferMessage(ctx context.Context, in *DeferRequest, opts ...grpc.CallOption) (*DeferResponse, error)
	DiscardMessage(ctx context.Context, in *DiscardRequest, opts ...grpc.CallOption) (*DiscardResponse, error)
	ReplayMessage(ctx context.Context, in *ReplayRequest, opts ...grpc.CallOption) (*ReplayResponse, error)
	// Flow Control
	PauseMessages(ctx context.Context, in *PauseRequest, opts ...grpc.CallOption) (*PauseResponse, error)
	ContinueMessages(ctx context.Context, in *ContinueRequest, opts ...grpc.CallOption) (*ContinueResponse, error)
}

type enSyncServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEnSyncServiceClient(cc grpc.ClientConnInterface) EnSyncServiceClient {
	return &enSyncServiceClient{cc}
}

func (c *enSyncServiceClient) Connect(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (*ConnectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConnectResponse)
	err := c.cc.Invoke(ctx, EnSyncService_Connect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *enSyncServiceClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, EnSyncService_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *enSyncServiceClient) PublishMessage(ctx context.Context, in *PublishMessageRequest, opts ...grpc.CallOption) (*PublishMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishMessageResponse)
	err := c.cc.Invoke(ctx, EnSyncService_PublishMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *enSyncServiceClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MessageStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EnSyncService_ServiceDesc.Streams[0], EnSyncService_Subscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRequest, MessageStreamResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EnSyncService_SubscribeClient = grpc.ServerStreamingClient[MessageStreamResponse]

func (c *enSyncServiceClient) Unsubscribe(ctx context.Context, in *UnsubscribeRequest, opts ...grpc.CallOption) (*UnsubscribeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnsubscribeResponse)
	err := c.cc.Invoke(ctx, EnSyncService_Unsubscribe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *enSyncServiceClient) AcknowledgeMessage(ctx context.Context, in *AcknowledgeRequest, opts ...grpc.CallOption) (*AcknowledgeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AcknowledgeResponse)
	err := c.cc.Invoke(ctx, EnSyncService_AcknowledgeMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *enSyncServiceClient) DeferMessage(ctx context.Context, in *DeferRequest, opts ...grpc.CallOption) (*DeferResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeferResponse)
	err := c.cc.Invoke(ctx, EnSyncService_DeferMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *enSyncServiceClient) DiscardMessage(ctx context.Context, in *DiscardRequest, opts ...grpc.CallOption) (*DiscardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DiscardResponse)
	err := c.cc.Invoke(ctx, EnSyncService_DiscardMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *enSyncServiceClient) ReplayMessage(ctx context.Context, in *ReplayRequest, opts ...grpc.CallOption) (*ReplayResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReplayResponse)
	err := c.cc.Invoke(ctx, EnSyncService_ReplayMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *enSyncServiceClient) PauseMessages(ctx context.Context, in *PauseRequest, opts ...grpc.CallOption) (*PauseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PauseResponse)
	err := c.cc.Invoke(ctx, EnSyncService_PauseMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *enSyncServiceClient) ContinueMessages(ctx context.Context, in *ContinueRequest, opts ...grpc.CallOption) (*ContinueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ContinueResponse)
	err := c.cc.Invoke(ctx, EnSyncService_ContinueMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EnSyncServiceServer is the server API for EnSyncService service.
// All implementations must embed UnimplementedEnSyncServiceServer
// for forward compatibility.
//
// Main EnSync service for client communication
type EnSyncServiceServer interface {
	// Connection & Authentication
	Connect(context.Context, *ConnectRequest) (*ConnectResponse, error)
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	// Message Publishing
	PublishMessage(context.Context, *PublishMessageRequest) (*PublishMessageResponse, error)
	// Message Subscription - Returns a stream of messages
	Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[MessageStreamResponse]) error
	Unsubscribe(context.Context, *UnsubscribeRequest) (*UnsubscribeResponse, error)
	// Message Management
	AcknowledgeMessage(context.Context, *AcknowledgeRequest) (*AcknowledgeResponse, error)
	DeferMessage(context.Context, *DeferRequest) (*DeferResponse, error)
	DiscardMessage(context.Context, *DiscardRequest) (*DiscardResponse, error)
	ReplayMessage(context.Context, *ReplayRequest) (*ReplayResponse, error)
	// Flow Control
	PauseMessages(context.Context, *PauseRequest) (*PauseResponse, error)
	ContinueMessages(context.Context, *ContinueRequest) (*ContinueResponse, error)
	mustEmbedUnimplementedEnSyncServiceServer()
}

// UnimplementedEnSyncServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEnSyncServiceServer struct{}

func (UnimplementedEnSyncServiceServer) Connect(context.Context, *ConnectRequest) (*ConnectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedEnSyncServiceServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedEnSyncServiceServer) PublishMessage(context.Context, *PublishMessageRequest) (*PublishMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PublishMessage not implemented")
}
func (UnimplementedEnSyncServiceServer) Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[MessageStreamResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedEnSyncServiceServer) Unsubscribe(context.Context, *UnsubscribeRequest) (*UnsubscribeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Unsubscribe not implemented")
}
func (UnimplementedEnSyncServiceServer) AcknowledgeMessage(context.Context, *AcknowledgeRequest) (*AcknowledgeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AcknowledgeMessage not implemented")
}
func (UnimplementedEnSyncServiceServer) DeferMessage(context.Context, *DeferRequest) (*DeferResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeferMessage not implemented")
}
func (UnimplementedEnSyncServiceServer) DiscardMessage(context.Context, *DiscardRequest) (*DiscardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DiscardMessage not implemented")
}
func (UnimplementedEnSyncServiceServer) ReplayMessage(context.Context, *ReplayRequest) (*ReplayResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReplayMessage not implemented")
}
func (UnimplementedEnSyncServiceServer) PauseMessages(context.Context, *PauseRequest) (*PauseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PauseMessages not implemented")
}
func (UnimplementedEnSyncServiceServer) ContinueMessages(context.Context, *ContinueRequest) (*ContinueResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ContinueMessages not implemented")
}
func (UnimplementedEnSyncServiceServer) mustEmbedUnimplementedEnSyncServiceServer() {}
func (UnimplementedEnSyncServiceServer) testEmbeddedByValue()                       {}

// UnsafeEnSyncServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EnSyncServiceServer will
// result in compilation errors.
type UnsafeEnSyncServiceServer interface {
	mustEmbedUnimplementedEnSyncServiceServer()
}

func RegisterEnSyncServiceServer(s grpc.ServiceRegistrar, srv EnSyncServiceServer) {
	// If the following call pancis, it indicates UnimplementedEnSyncServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EnSyncService_ServiceDesc, srv)
}

func _EnSyncService_Connect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnSyncServiceServer).Connect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnSyncService_Connect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnSyncServiceServer).Connect(ctx, req.(*ConnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnSyncService_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnSyncServiceServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnSyncService_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnSyncServiceServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnSyncService_PublishMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnSyncServiceServer).PublishMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnSyncService_PublishMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnSyncServiceServer).PublishMessage(ctx, req.(*PublishMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnSyncService_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EnSyncServiceServer).Subscribe(m, &grpc.GenericServerStream[SubscribeRequest, MessageStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EnSyncService_SubscribeServer = grpc.ServerStreamingServer[MessageStreamResponse]

func _EnSyncService_Unsubscribe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnsubscribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnSyncServiceServer).Unsubscribe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnSyncService_Unsubscribe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnSyncServiceServer).Unsubscribe(ctx, req.(*UnsubscribeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnSyncService_AcknowledgeMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcknowledgeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnSyncServiceServer).AcknowledgeMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnSyncService_AcknowledgeMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnSyncServiceServer).AcknowledgeMessage(ctx, req.(*AcknowledgeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnSyncService_DeferMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnSyncServiceServer).DeferMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnSyncService_DeferMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnSyncServiceServer).DeferMessage(ctx, req.(*DeferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnSyncService_DiscardMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiscardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnSyncServiceServer).DiscardMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnSyncService_DiscardMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnSyncServiceServer).DiscardMessage(ctx, req.(*DiscardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnSyncService_ReplayMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnSyncServiceServer).ReplayMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnSyncService_ReplayMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnSyncServiceServer).ReplayMessage(ctx, req.(*ReplayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnSyncService_PauseMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PauseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnSyncServiceServer).PauseMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnSyncService_PauseMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnSyncServiceServer).PauseMessages(ctx, req.(*PauseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnSyncService_ContinueMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContinueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnSyncServiceServer).ContinueMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnSyncService_ContinueMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnSyncServiceServer).ContinueMessages(ctx, req.(*ContinueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EnSyncService_ServiceDesc is the grpc.ServiceDesc for EnSyncService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EnSyncService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ensync.EnSyncService",
	HandlerType: (*EnSyncServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Connect",
			Handler:    _EnSyncService_Connect_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _EnSyncService_Heartbeat_Handler,
		},
		{
			MethodName: "PublishMessage",
			Handler:    _EnSyncService_PublishMessage_Handler,
		},
		{
			MethodName: "Unsubscribe",
			Handler:    _EnSyncService_Unsubscribe_Handler,
		},
		{
			MethodName: "AcknowledgeMessage",
			Handler:    _EnSyncService_AcknowledgeMessage_Handler,
		},
		{
			MethodName: "DeferMessage",
			Handler:    _EnSyncService_DeferMessage_Handler,
		},
		{
			MethodName: "DiscardMessage",
			Handler:    _EnSyncService_DiscardMessage_Handler,
		},
		{
			MethodName: "ReplayMessage",
			Handler:    _EnSyncService_ReplayMessage_Handler,
		},
		{
			MethodName: "PauseMessages",
			Handler:    _EnSyncService_PauseMessages_Handler,
		},
		{
			MethodName: "ContinueMessages",
			Handler:    _EnSyncService_ContinueMessages_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _EnSyncService_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "internal/proto/ensync.proto",
}
