version: "2"
run:
  go: "1.24"
output:
  formats:
    text:
      path: stderr
      print-linter-name: true
  sort-order:
    - linter
    - severity
    - file
linters:
  default: none
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - copyloopvar
    - cyclop
    - dogsled
    - durationcheck
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - funlen
    - gocheckcompilerdirectives
    - goconst
    - gocritic
    - gocyclo
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - mnd
    - nakedret
    - noctx
    - nolintlint
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace

  settings:
    cyclop:
      max-complexity: 15
    dupl:
      threshold: 100
    funlen:
      lines: 100
      statements: 50
    goconst:
      min-len: 2
      min-occurrences: 2
    gocritic:
      disabled-checks:
        - dupImport
        - ifElseChain
        - octalLiteral
        - wrapperFunc
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    govet:
      settings:
        printf:
          funcs:
            - (github.com/EnSync-engine/Go-SDK/common.Logger).Infof
            - (github.com/EnSync-engine/Go-SDK/common.Logger).Warnf
            - (github.com/EnSync-engine/Go-SDK/common.Logger).Errorf
            - (github.com/EnSync-engine/Go-SDK/common.Logger).Fatalf
    lll:
      line-length: 140
    misspell:
      locale: US
    mnd:
      checks:
        - argument
        - case
        - condition
        - return
    nolintlint:
      require-explanation: false
      require-specific: false
      allow-unused: false
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - funlen
          - mnd
        path: _test\.go
      - linters:
          - gocritic
        text: "unnecessaryDefer:"
      - linters:
          - gocritic
        text: "whyNoLint:"
      - linters:
          - lll
        source: "^//go:generate "
      - linters:
          - cyclop
        path: (.+)_test\.go
    paths:
      - test/testdata_etc
      - internal/cache
      - internal/renameio
      - internal/robustio
      - third_party$
      - builtin$
      - examples$
      - proto$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/EnSync-engine/Go-SDK
  exclusions:
    generated: lax
    paths:
      - test/testdata_etc
      - internal/cache
      - internal/renameio
      - internal/robustio
      - third_party$
      - builtin$
      - examples$
      - proto$
